### Get list of connections
GET {{base_url}}/api/connection
Authorization: Basic {{admin_username}} {{admin_password}}
#Authorization: Basic {{user1_username}} {{user1_password}}

### Get users
GET {{base_url}}/api/user
Authorization: Basic {{admin_username}} {{admin_password}}
#Authorization: Basic {{user1_username}} {{user1_password}}

### Create a new regular user1
POST {{base_url}}/api/user?username={{user1_username}}&password={{user1_password}}
Authorization: Basic {{admin_username}} {{admin_password}}

### Create a new regular user1 form
POST {{base_url}}/api/user
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{admin_username}} {{admin_password}}

username = {{user1_username}} &
password = {{user1_password}}

### Creating wrong user
POST {{base_url}}/api/user
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{admin_username}} {{admin_password}}

username = a-b &
password = 1qaz

### Get a current user
GET {{base_url}}/api/user/self
Authorization: Basic {{user1_username}} {{user1_password}}

### Change password for a user
PUT localhost:8080/api/user/self?old={{admin_password}}&new={{user1_password}}
Authorization: Basic {{user1_username}} {{user1_password}}

### Create a new admin user
POST {{base_url}}/api/user?username={{user2_username}}&password={{user2_password}}&role=admin
Authorization: Basic {{admin_username}} {{admin_password}}

### Update user2
PUT {{base_url}}/api/user/{{user2_username}}?password={{user2_password}}&role=user
Authorization: Basic {{admin_username}} {{admin_password}}

### Delete a user1
DELETE {{base_url}}/api/user/{{user1_username}}
Authorization: Basic {{admin_username}} {{admin_password}}

### Delete a user2
DELETE {{base_url}}/api/user/{{user2_username}}?force=true
Authorization: Basic {{admin_username}} {{admin_password}}

### Get history
GET {{base_url}}/api/connection/history?ch=168.1&th=dms&tp=22,2020&oa=2025-08-07T21:03
#GET {{base_url}}/api/connection/history?id=11844568-0e57-448f-b80f-e50e50b42572,90625f93-2d93-4617-a360-c276af6f29ca
#GET {{base_url}}/api/connection/history?un=md03375
Authorization: Basic {{admin_username}} {{admin_password}}
#Authorization: Basic {{user1_username}} {{user1_password}}

###

