spring:
  application.name: soht2-client
  main:
    banner-mode: off
    web-application-type: none
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null

logging.level:
  root: info

soht2.client:
  url: http://localhost:8080/api/connection
  socket-accept-timeout: PT10S
  socket-read-timeout: PT0.1S
  read-buffer-size: 16KB
  poll-strategy: exponent
  #username: soht2
  #password: password_of_soht2
