spring:
  application.name: soht2-client
  main:
    banner-mode: off
    web-application-type: none
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
  profiles.include: client

logging.level:
  root: info

soht2.client:
  url: http://localhost:8080/api/connection
  socket-read-timeout: PT0.1S
  read-buffer-size: 64KB
  compression:
    type: none
    min-request-size: 2KB
  poll:
    strategy: exponent
    initial-delay: PT0.1S
    max-delay: PT5S
    factor: 5
