@startuml
'https://plantuml.com/component-diagram
title Component Diagram for SOHT2 Client-Server Architecture

'------------------------------------------------------------------------------
' Client Host
node "Client Host" {
  interface "Port A" as CPA
  interface "Port B" as CPB

  component "Local Client" as CA
  note top of CA {
    Connects to
    "Local Service"
  }

  component "SOHT2 Client" as SOHTC
  note top of SOHTC {
   May be configured to forward ports to any services.
   "Port A" and "Port B" are forwarded here to
   "Service Port A" and "Service Port B" respectively.
  }

  CPA = SOHTC
  SOHTC = CPB

  CA -( CPA
}

'------------------------------------------------------------------------------
' Remote Client
component "Remote Client" as CB
note top of CB {
  Connects to
  "Remote Service"
}
CPB )- CB

'------------------------------------------------------------------------------
' Server Host
node "Server Host" {
  interface "HTTP(S)" as HTTPS

  interface "Service\nPort A" as SPA
  note top of SPA {
    Forwarded
    "Port A"
  }

  component "Local Service" as SA
  note top of SA {
    Connected with
    "Local Client"
  }

  component "SOHT2 Server" as SOHTS
  note bottom of SOHTS {
    Opened ports correspond to configured ones on "SOHT Client"
  }

  HTTPS == SOHTS
  SA = SPA
  SPA )- SOHTS
}

'------------------------------------------------------------------------------
' Remote Service
interface "Service\nPort B" as SPB
note top of SPB {
  Forwarded
  "Port B"
}
component "Remote Service" as SB
note bottom of SB {
  Connected with
  "Remote Client"
}
SPB = SB
SOHTS -( SPB

'------------------------------------------------------------------------------
' Proxy
SOHTC --> [Proxy]: <<http(s)>>
[Proxy] --( HTTPS: <<http(s)>>
note right of Proxy {
  Optional proxy for HTTP requests
}

@enduml