@startuml
'https://plantuml.com/sequence-diagram
title Sequence Diagram for Client-Server SOHT2 Connection

'autonumber
activate "SOHT2 Client"

"SOHT2 Client" -> "Client Socket" **: open socket

"SOHT2 Client" -> "SOHT2 Server" ++: open session
"SOHT2 Server" -> "Target Socket" **: open socket
"SOHT2 Server" --> "SOHT2 Client" --: done

alt exchange

  loop while connection is open and no errors

    "SOHT2 Client" -> "Client Socket" ++: read buffer
    note right of "Client Socket": reads to buffer with timeout
    "SOHT2 Client" <-- "Client Socket" --: return data_in

    "SOHT2 Client" -> "SOHT2 Server" ++: exchange data_in

    "SOHT2 Server" -> "Target Socket" ++: write data_in
    note left of "Target Socket": optional - if data_in isn't empty
    "SOHT2 Server" <-- "Target Socket" --: done

    "SOHT2 Server" -> "Target Socket" ++: read buffer
    note left of "Target Socket": reads to buffer with timeout
    "SOHT2 Server" <-- "Target Socket" --: return data_out

    "SOHT2 Client" <-- "SOHT2 Server" --: return data_out

    "SOHT2 Client" -> "Client Socket" ++: write data_out
    note right of "Client Socket": optional - if data_out isn't empty
    "SOHT2 Client" <-- "Client Socket" --: done

    "SOHT2 Client" -> "SOHT2 Client": delay
    note right: computed on empty data exchange from 0 to poll.maxDelay

  end loop

else on connection close or error

  "SOHT2 Client" -> "SOHT2 Server" ++: close session
  "SOHT2 Server" -> "Target Socket" !!: close socket
  "SOHT2 Client" <-- "SOHT2 Server" --: done

  "SOHT2 Client" -> "Client Socket" !!: close socket

end alt

@enduml