#!/bin/bash
# SOHT2 © Licensed under MIT 2025.
# Client Control Script
# ------------------------------------------------------

# Application configuration
APP_NAME="SOHT2 Client"
APP_FILE="$(basename "$0")"
APP_HOME="$(dirname "$(readlink -f "$0")")"
if [[ "$OSTYPE" =~ ^cygwin|msys|mingw ]]; then
  APP_HOME="$(cygpath -w "$APP_HOME")"
fi
APP_JAR="${APP_HOME}/${APP_FILE}.jar"
PID_FILE="${APP_HOME}/${APP_FILE}.pid"
LOG_FILE="${APP_HOME}/${APP_FILE}.log"

# Exit codes
ERR_RUNNING=1
ERR_START=2
ERR_NO_PID=3
ERR_EMPTY_PID=4
ERR_WRONG_PID=5
ERR_STOP=6
ERR_NO_JAVA=7
ERR_JAVA_VER=8
ERR_NO_LOG=9

# ------------------------------------------------------
# Check if the Java runtime is available and meets the minimum version requirement
function check_java() {
  JAVA_HOME="${JAVA_HOME:-$(which java | sed -rn 's|^(.+)/bin/java$|\1|p')}"
  JAVA_CMD="${JAVA_HOME}/bin/java"
  if [[ ! -x "${JAVA_CMD}" ]]; then
    echo >&2 "Java is not installed or not found in PATH."
    exit $ERR_NO_JAVA
  fi
  local JAVA_VER
  JAVA_VER=$("${JAVA_CMD}" -version 2>&1 | grep version | cut -d\" -f2 | cut -d. -f1)
  if [[ "${JAVA_VER}" -lt 21 ]]; then
    echo >&2 "Java version is ${JAVA_VER}, which is less than 21."
    exit $ERR_JAVA_VER
  fi
  JAVA_OPTS="${JAVA_OPTS:--Xmx256m -server -Djava.awt.headless=true} -Dspring.pid.file=${PID_FILE}"
}

# ------------------------------------------------------
# Check if the application is running and set APP_PID if it is
function app_pid() {
  [[ ! -e "${PID_FILE}" ]] && return $ERR_NO_PID
  APP_PID="$(cat "${PID_FILE}" 2>/dev/null)"
  [[ -z "${APP_PID}" ]] && return $ERR_EMPTY_PID
  local PS_CMD
  if [[ "$OSTYPE" =~ ^cygwin|msys|mingw ]]; then
    PS_CMD="ps | awk '{print \$4}' | grep -q ${APP_PID}"
  else
    PS_CMD="ps -p ${APP_PID} >/dev/null"
  fi
  if ! eval "${PS_CMD}"; then
    unset APP_PID
    return $ERR_WRONG_PID
  fi
  return 0
}

# ------------------------------------------------------
# Start the application if it's not already running
function start() {
  if app_pid; then
    echo >&2 "${APP_NAME} is already running with PID ${APP_PID}"
    exit $ERR_RUNNING
  fi
  check_java
  echo -n "Starting ${APP_NAME}... "
  cd "${APP_HOME}" || exit $ERR_START
  eval "${JAVA_CMD} ${JAVA_OPTS}" -jar "${APP_JAR}" >>"${LOG_FILE}" 2>&1 &
  for _ in {1..10}; do
    sleep 1
    if app_pid; then
      echo "SUCCESS"
      exit 0
    fi
  done
  echo "FAILURE"
  exit $ERR_START
}

# ------------------------------------------------------
# Stop the application if it's running
function stop() {
  status
  echo -n "Stopping ${APP_NAME}... "
  local KILL_CMD
  if [[ "$OSTYPE" =~ ^cygwin|msys|mingw ]]; then
    KILL_CMD="/bin/kill -W"
  else
    KILL_CMD="kill"
  fi
  if ! eval "${KILL_CMD} ${APP_PID}" 2>/dev/null; then
    echo "FAILURE"
    exit $ERR_STOP
  fi
  for _ in {1..10}; do
    sleep 1
    if ! app_pid; then
      rm "${PID_FILE}" 2>/dev/null
      if [[ -e "${LOG_FILE}" ]]; then
        mv "${LOG_FILE}" "${APP_HOME}/${APP_FILE}.$(date +%Y%m%d%H%M%S).log" >/dev/null 2>&1
      fi
      echo "SUCCESS"
      exit 0
    fi
  done
  echo "FAILURE"
  exit $ERR_STOP
}

# ------------------------------------------------------
# Check the status of the application
function status() {
  app_pid
  local STATUS=$?
  case $STATUS in
  0) return 0 ;;
  "$ERR_NO_PID") echo >&2 "${APP_NAME}'s PID file doesn't exist" ;;
  "$ERR_EMPTY_PID") echo >&2 "${APP_NAME}'s PID file exists but empty" ;;
  "$ERR_WRONG_PID") echo >&2 "${APP_NAME}'s is not running but PID file exists" ;;
  *) echo >&2 "${APP_NAME}'s status code is ${STATUS}" ;;
  esac
  exit $STATUS
}

# ------------------------------------------------------
# Display the most recent log file using `less` command
function log() {
  local LAST_LOG
  LAST_LOG="$(find "$APP_HOME" -type f -name "${APP_FILE}*.log" -print0 | xargs -0 ls -1t | head -1)"
  if [[ -z "$LAST_LOG" ]]; then
    echo >&2 "No log files found."
    exit $ERR_NO_LOG
  fi
  echo "Displaying the last log file: ${LAST_LOG}"
  less "${LAST_LOG}"
}

# ------------------------------------------------------
# Main script logic
case "${1}" in
start) start ;;
stop) stop ;;
log) log ;;
restart)
  # shellcheck disable=SC2005 # Using command substitution to avoid exiting the script
  echo "$(stop)"
  start
  ;;
status)
  status
  echo "${APP_NAME} is running with PID ${APP_PID}"
  ;;
*)
  echo "${APP_NAME} Control Script © Licensed under MIT 2026"
  echo "Usage: ${0} {start|stop|restart|status|log}"
  ;;
esac
