#!/bin/bash

APP_NAME="SOHT2 Client"
APP_FILE="$(basename "$0")"
LOG_NAME="${APP_FILE}.log"
APP_HOME="$(dirname "$(readlink -f "$0")")"

if [[ "$OSTYPE" =~ ^cygwin|msys|mingw ]]; then
  APP_HOME="$(cygpath -w "$APP_HOME")"
fi

APP_JAR="${APP_HOME}/${APP_FILE}.jar"
PID_FILE="${APP_HOME}/${APP_FILE}.pid"
LOG_FILE="${APP_HOME}/${LOG_NAME}"

function check_java() {
  JAVA_HOME="${JAVA_HOME:-$(which java | sed -rn 's|^(.+)/bin/java$|\1|p')}"
  JAVA_CMD="${JAVA_HOME}/bin/java"
  if [[ ! -x "${JAVA_CMD}" ]]; then
    echo >&2 "Java is not installed or not found in PATH."
    exit 7
  fi
  local JAVA_VER
  JAVA_VER=$("${JAVA_CMD}" -version 2>&1 | grep version | cut -d\" -f2 | cut -d. -f1)
  if [[ "${JAVA_VER}" -lt 21 ]]; then
    echo >&2 "Java version is ${JAVA_VER}, which is less than 21."
    exit 8
  fi
  JAVA_OPTS="${JAVA_OPTS:--Xmx256m -server -Djava.awt.headless=true} -Dspring.pid.file=${PID_FILE}"
}

function app_pid() {
  [[ ! -e "${PID_FILE}" ]] && return 3
  APP_PID="$(cat "${PID_FILE}" 2>/dev/null)"
  [[ -z "${APP_PID}" ]] && return 4
  local PS_CMD
  if [[ "$OSTYPE" =~ ^cygwin|msys|mingw ]]; then
    PS_CMD="ps | awk '{print \$4}' | grep -q ${APP_PID}"
  else
    PS_CMD="ps -p ${APP_PID} >/dev/null"
  fi
  # shellcheck disable=SC2086 # PS_CMD contains multiple arguments
  if ! eval $PS_CMD; then
    unset APP_PID
    return 5
  fi
  return 0
}

function start() {
  if app_pid; then
    echo >&2 "${APP_NAME} is already running with PID ${APP_PID}"
    exit 1
  fi
  check_java
  echo -n "Starting ${APP_NAME}... "
  cd "${APP_HOME}" || exit 2
  # shellcheck disable=SC2086 # JAVA_OPTS contains multiple items
  "${JAVA_CMD}" $JAVA_OPTS -jar "${APP_JAR}" >>"${LOG_FILE}" 2>&1 &
  for _ in {1..10}; do
    sleep 1
    if [[ -e "${PID_FILE}" ]]; then
      echo "SUCCESS"
      exit 0
    fi
  done
  echo "FAILURE"
  exit 2
}

function stop() {
  status
  echo -n "Stopping ${APP_NAME}... "
  local KILL_CMD
  if [[ "$OSTYPE" =~ ^cygwin|msys|mingw ]]; then
    KILL_CMD="/bin/kill -W"
  else
    KILL_CMD="kill"
  fi
  # shellcheck disable=SC2086 # KILL_CMD may contain multiple arguments
  if ! eval ${KILL_CMD} ${APP_PID} 2>/dev/null; then
    echo "FAILURE"
    exit 6
  fi
  for _ in {1..10}; do
    sleep 1
    if ! app_pid; then
      rm "${PID_FILE}" 2>/dev/null
      if [[ -e "${LOG_FILE}" ]]; then
        mv "${LOG_FILE}" "${APP_HOME}/${APP_FILE}.$(date +%Y%m%d%H%M%S).log" >/dev/null 2>&1
      fi
      echo "SUCCESS"
      exit 0
    fi
  done
  echo "FAILURE"
  exit 6
}

function status() {
  app_pid
  local STATUS=$?
  case $STATUS in
  0) return 0 ;;
  3) echo >&2 "${APP_NAME}'s PID file doesn't exist" ;;
  4) echo >&2 "${APP_NAME}'s PID file exists but empty" ;;
  5) echo >&2 "${APP_NAME}'s is not running but PID file exists" ;;
  *) echo >&2 "${APP_NAME}'s status code is ${STATUS}" ;;
  esac
  exit $STATUS
}

function log() {
  local LAST_LOG
  LAST_LOG="$(find "$APP_HOME" -type f -name "${APP_FILE}*.log" -print0 | xargs -0 ls -1t | head -1)"
  if [[ -z "$LAST_LOG" ]]; then
    echo >&2 "No log files found."
    exit 9
  fi
  echo "Displaying the last log file: ${LAST_LOG}"
  less "${LAST_LOG}"
}

case "${1}" in
start)
  start
  ;;
stop)
  stop
  ;;
restart)
  # shellcheck disable=SC2005 # Using command substitution to avoid exiting the script
  echo "$(stop)"
  sleep 1
  start
  ;;
status)
  status
  echo "${APP_NAME} is running with PID ${APP_PID}"
  ;;
log)
  log
  ;;
*)
  echo "Usage: ${0} {start|stop|restart|status|log}"
  echo "Exit codes:"
  echo "  0 - Success"
  echo "  1 - Already running"
  echo "  2 - Start failure"
  echo "  3 - PID file doesn't exist"
  echo "  4 - PID file exists but empty"
  echo "  5 - Not running but PID file exists"
  echo "  6 - Stop failure"
  echo "  7 - Java not installed or not found in PATH"
  echo "  8 - Java version is less than 21"
  echo "  9 - Log file not found"
  ;;
esac
