spring:
  application.name: soht2-server
  main.banner-mode: off
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null

server:
  address: 0.0.0.0
  shutdown: graceful
  error.include-message: always
  compression.enabled: true

management:
  endpoints:
    web:
      exposure.include: '*'
      cors:
        allowed-headers: '*'
        allowed-methods:
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
          - HEAD
          - OPTIONS
        allowed-origins: '*'

logging.level:
  root: info

soht2.server:
  socket-timeout: PT0.1S
  read-buffer-size: 16KB
