spring:
  application.name: soht2-server
  profiles.include: server
  devtools.add-properties: false
  main.banner-mode: off
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
  datasource:
    url: jdbc:h2:file:${soht2.server.database-path}
    username: ${soht2.server.admin-username}
    password: ${soht2.server.default-admin-password}
    hikari:
      auto-commit: false
      maximum-pool-size: 5
  jpa:
    open-in-view: true
    hibernate.ddl-auto: update
  cache:
    cache-names: userCache
    type: caffeine
    caffeine.spec: maximumSize=1000,expireAfterWrite=${soht2.server.user-cache-ttl}
  h2.console:
    enabled: true
    settings.web-allow-others: true

management:
  endpoints:
    web:
      exposure.include: '*'
      cors:
        allowed-headers: '*'
        allowed-methods:
          - GET
          - POST
          - PUT
          - DELETE
          - HEAD
          - OPTIONS
        allowed-origins: '*'

logging.level:
  root: info

server:
  address: 0.0.0.0
  shutdown: graceful
  error:
    include-message: always
    include-stacktrace: on_param
    include-exception: true
  compression:
    enabled: true
    min-response-size: 2KB
    mime-types:
      - text/plain
      - text/html
      - text/xml
      - text/css
      - text/javascript
      - application/json
      - application/xml
      - application/javascript
      - application/octet-stream
  forward-headers-strategy: native

soht2.server:
  socket-read-timeout: PT0.1S
  read-buffer-size: 64KB
  user-cache-ttl: PT10M
  database-path: ./soht2
  admin-username: admin
  open-api-server-url: http://localhost:8080
  abandoned-connections:
    timeout: PT1M
    check-interval: PT5S

springdoc.swagger-ui.path: /swagger-ui