spring:
  application.name: soht2-server
  profiles.include: server
  devtools.add-properties: false
  main.banner-mode: off
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
  datasource:
    url: jdbc:h2:file:${soht2.server.database.path}
    username: soht2
    driver-class-name: org.h2.Driver
    hikari:
      auto-commit: false
      driver-class-name: ${spring.datasource.driver-class-name}
      maximum-pool-size: 5
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: true
    hibernate.ddl-auto: update
  cache:
    cache-names: userCache
    type: caffeine
    caffeine.spec: maximumSize=1000,expireAfterWrite=${soht2.server.user-cache-ttl}

management:
  endpoints:
    web:
      exposure.include: '*'
      cors:
        allowed-headers: '*'
        allowed-methods:
          - GET
          - POST
          - PUT
          - DELETE
          - HEAD
          - OPTIONS
        allowed-origins: '*'

logging.level:
  root: info

server:
  address: 0.0.0.0
  shutdown: graceful
  error:
    include-message: always
    include-stacktrace: on_param
    include-exception: true
  compression:
    enabled: true
    min-response-size: 2KB
    mime-types:
      - text/plain
      - text/html
      - text/xml
      - text/css
      - text/javascript
      - application/json
      - application/xml
      - application/javascript
      - application/octet-stream

soht2.server:
  socket-read-timeout: PT0.1S
  read-buffer-size: 64KB
  user-cache-ttl: PT10M
  database:
    path: ./soht2
    admin-username: admin
  abandoned-connections:
    timeout: PT1M
    check-interval: PT5S
  open-api:
    server-url: http://localhost:8080
    server-description: SOHT2 OpenAPI Server
